### ISSUE TITLE
Write a playbook to fetch the playbooks from the Ansible repo

### ISSUE THREAD

**Issue by gridhead** [CentOS/duffy#88]
We have Ansible Playbooks that are not used immediately by the code but we need a way to fetch the same while installing Duffy via Poetry/DNF.

**Comment by siddharthvipul** [comment]
https://github.com/CentOS/ansible-role-duffy exists and the reason is for installing the duffy in CentOS Infra (so centos specific playbooks for seamicros, opennebula etc)
we can update that to pull latest release from duffy and then clone rest of the playbook
This seems like a simpler approach instead of going submodules route (and then updating both places on changes)

note: I am suggesting this as it seems simpler.. prove me wrong and keep all in one place, I would be happy with that too :V

**Comment by nphilipp** [comment]
While `ansible-role-duffy` only covers the generic part of installing Duffy, the concrete configuration of nodepools and the related Ansible playbooks are covered in CentOS infra playbooks. Closing.
